version: "3.7"

services:
    registry:
        container_name: registry
        image: "registry:2"
        environment:
          - REGISTRY_STORAGE_DELETE_ENABLED=true
        volumes:
          - ./registry_volume:/var/lib/registry
        restart: always
        ports:
            - "5000:5000"
