version: "3.7"

services:

  db:
    container_name: db
    image: postgis/postgis:12-3.0-alpine
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: extremly_secure_password
    ports:
      - "5432:5432"
    restart: always
    networks:
      - mynetwork
    labels:
      - "com.centurylinklabs.watchtower.scope=external"

  redis:
    container_name: redis
    image: "redis:6.2-alpine"
    ports:
      - "6379:6379"
    restart: always
    networks:
      - mynetwork
    labels:
      - "com.centurylinklabs.watchtower.scope=external"

  django-base:
    image: localhost:5000/testapp/django:latest
    profile:
      - 'update-only' # prevents auto-start
    labels:
      com.centurylinklabs.watchtower.scope: internal-pull
      
  django:
    container_name: django
    image: localhost:5000/testapp/django:latest
    ports:
      - "9000:9000"
    restart: always
    networks:
      - mynetwork
    depends_on:
      - db
      - redis
    labels:
      com.centurylinklabs.watchtower.scope: local-update

  nginx-base:
    image: nginx:1.19-alpine
    profile:
      - 'update-only'
    labels:
      com.centurylinklabs.watchtower.scope: external

  nginx:
    container_name: nginx
    image: nginx:1.19-alpine
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    networks:
      - mynetwork
    depends_on: 
      - django
    labels:
      com.centurylinklabs.watchtower.scope: local-update
      com.centurylinklabs.watchtower.depends-on: django

  watchtower-int:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --scope internal-pull --include-stopped --no-restart
    restart: always
    networks:
      - mynetwork
    labels:
      - "com.centurylinklabs.watchtower.scope=internal-pull"

  watchtower-ext:
    container_name: watchtower-ext
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope external --include-stopped --cleanup
    restart: always
    networks:
      - mynetwork
    labels:
      - "com.centurylinklabs.watchtower.scope=external"

  watchtower-local:
    container_name: watchtower-upd
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --scope local-update --no-pull --cleanup
    restart: always
    depends_on:
      - watchtower-int
    networks:
      - mynetwork
    labels:
      - "com.centurylinklabs.watchtower.scope=local-update"

networks:
  mynetwork:
    name: mynetwork
      
